version: "3"
services:
    stickyDB:
        container_name: sticky_db
        image: mysql
        ports:
            - "3306:3306"
        volumes:
            # 初期データを投入するSQLが格納されているdir
            - ./data/mysql_init:/docker-entrypoint-initdb.d
            # 永続化するときにマウントするdir
            - ./data/mysql_data:/var/lib/mysql
            - ./data/mysql_conf/default_authentication.cnf:/etc/mysql/conf.d/default_authentication.cnf
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: test
            MYSQL_PASSWORD: test
    stickyApp:
        container_name: sticky_app
        image: python
        ports:
            - "8080:8080"
        volumes:
            - "./stickyBoards_Server:/var/www/html"
            - "./requirements.txt:/tmp/requirements.txt"
        environment:
            STICKY_BOARDS_DB_ID: root
            STICKY_BOARDS_DB_PASS: root
            STICKY_BOARDS_DB_LOCATION: sticky_db
        working_dir: /var/www/html
        command: >
            bash -c "apt-get install libmariadb-dev && 
            pip install -r /tmp/requirements.txt &&
            python ./main.py"